# Generated by Django 3.2.9 on 2022-01-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220110_1004'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
            ],
        ),
    ]
